In [1]:
import pandas as pd

messages = pd.read_csv('SMSSpamCollection.txt',sep='\t',names=['label','message'])
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [2]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
messages.shape

(5572, 2)

In [4]:
import nltk
import re 

In [5]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [6]:
messages.iloc[0,1]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [11]:
review=re.sub('[^a-zA-z]',' ',messages.iloc[0,1])
review

'Go until jurong point  crazy   Available only in bugis n great world la e buffet    Cine there got amore wat   '

In [13]:
review.lower()

'go until jurong point  crazy   available only in bugis n great world la e buffet    cine there got amore wat   '

In [7]:
corpus = []
for i in range(len(messages)):
    review = re.sub('[^a-zA-z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)


In [8]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500,ngram_range=(1,2))

In [20]:
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%.3g" % x))
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [22]:
cv.vocabulary_

{'go': 791,
 'point': 1619,
 'crazi': 451,
 'avail': 112,
 'bugi': 237,
 'great': 858,
 'world': 2441,
 'la': 1104,
 'cine': 354,
 'got': 839,
 'wat': 2355,
 'ok': 1463,
 'lar': 1115,
 'joke': 1074,
 'wif': 2407,
 'oni': 1484,
 'ok lar': 1466,
 'free': 719,
 'entri': 622,
 'wkli': 2431,
 'comp': 402,
 'win': 2412,
 'cup': 468,
 'final': 687,
 'st': 2017,
 'may': 1266,
 'text': 2121,
 'receiv': 1734,
 'question': 1692,
 'std': 2030,
 'txt': 2231,
 'rate': 1709,
 'appli': 76,
 'free entri': 724,
 'entri wkli': 624,
 'cup final': 469,
 'std txt': 2031,
 'txt rate': 2237,
 'rate appli': 1711,
 'dun': 583,
 'say': 1843,
 'earli': 589,
 'alreadi': 49,
 'nah': 1375,
 'think': 2141,
 'goe': 814,
 'usf': 2297,
 'live': 1179,
 'around': 88,
 'though': 2149,
 'freemsg': 731,
 'hey': 940,
 'darl': 493,
 'week': 2375,
 'word': 2437,
 'back': 129,
 'like': 1165,
 'fun': 747,
 'still': 2033,
 'tb': 2101,
 'xxx': 2468,
 'send': 1882,
 'rcv': 1717,
 'even': 632,
 'brother': 225,
 'speak': 2001,
 'treat

In [36]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
y2 = pd.get_dummies(messages['label'],dtype=int)
y2

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [10]:
y2=y2.iloc[:,0].values
y2

array([1, 1, 0, ..., 1, 1, 1])

In [11]:
y2.shape

(5572,)

In [27]:
y = pd.get_dummies(messages['label'])

In [28]:
y=y.iloc[:,0].values
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [29]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
spam_detect_model=MultinomialNB().fit(X_train,y_train)

In [32]:
y_pred=spam_detect_model.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score,classification_report

In [34]:
accuracy_score(y_test,y_pred)

0.9919282511210762

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.99      0.94      0.97       141
        True       0.99      1.00      1.00       974

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [23]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(corpus,y2,test_size=0.2)

In [24]:
X_train

['hot live fantasi call p per min ntt ltd po box croydon cr wb nation rate call',
 'wiskey brandi rum gin beer vodka scotch shampain wine kudi yarasu dhina vaazhthukk',
 '[ ] anyway mani good even u',
 'ok lor',
 'guess lt gt min',
 'hey j r u feel better hopeso hunni amnow feelin ill ithink may tonsolitusaswel damn iam layin bedreal bore lotsof luv xxxx',
 'doubl min doubl txt price linerent latest orang bluetooth mobil call mobileupd latest offer call optout lf',
 'will go app class',
 'know u u know send chat let find p msg rcvd hg suit land row w j hl ldn year',
 'curiou cuz ask',
 'congrat nokia video camera phone call call cost ppm ave call min vari mobil close post bcm ldn wc n xx',
 'day class class',
 'stop get ice cream go back',
 'urgent tri contact u today draw show prize guarante call land line claim valid hr',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'problem talk later',
 'aight text address',
 'wait til least wedne

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500,ngram_range=(1,2))
X_train = tv.fit_transform(raw_documents=X_train).toarray()
X_test = tv.transform(raw_documents=X_test).toarray()

In [26]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
tv.vocabulary_

{'hot': 961,
 'live': 1161,
 'fantasi': 651,
 'call': 237,
 'per': 1536,
 'min': 1295,
 'ntt': 1447,
 'ltd': 1212,
 'po': 1589,
 'box': 196,
 'croydon': 442,
 'cr': 433,
 'wb': 2350,
 'nation': 1386,
 'rate': 1673,
 'hot live': 962,
 'live fantasi': 1162,
 'fantasi call': 652,
 'call per': 254,
 'per min': 1537,
 'min ntt': 1298,
 'ntt ltd': 1448,
 'ltd po': 1213,
 'po box': 1590,
 'box croydon': 197,
 'croydon cr': 443,
 'cr wb': 434,
 'wb nation': 2351,
 'nation rate': 1387,
 'rate call': 1676,
 'beer': 157,
 'wine': 2404,
 'anyway': 75,
 'mani': 1243,
 'good': 815,
 'even': 619,
 'good even': 819,
 'ok': 1468,
 'lor': 1184,
 'ok lor': 1471,
 'guess': 871,
 'lt': 1208,
 'gt': 851,
 'lt gt': 1210,
 'gt min': 857,
 'hey': 914,
 'feel': 664,
 'better': 163,
 'hunni': 980,
 'ill': 995,
 'may': 1263,
 'damn': 470,
 'iam': 985,
 'bore': 189,
 'luv': 1221,
 'xxxx': 2469,
 'feel better': 665,
 'doubl': 552,
 'txt': 2198,
 'price': 1627,
 'linerent': 1156,
 'latest': 1106,
 'orang': 1497,
 'b

In [28]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [29]:

#prediction
y_pred=spam_tfidf_model.predict(X_test)

In [30]:
score=accuracy_score(y_test,y_pred)
print(score)

0.9775784753363229


In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.17      0.14      0.15       153
           1       0.87      0.89      0.88       962

    accuracy                           0.79      1115
   macro avg       0.52      0.51      0.52      1115
weighted avg       0.77      0.79      0.78      1115



In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.84      1.00      0.91       132
           1       1.00      0.97      0.99       983

    accuracy                           0.98      1115
   macro avg       0.92      0.99      0.95      1115
weighted avg       0.98      0.98      0.98      1115

