In [1]:
data = "As an IT professional with a total of 6 years of experience, including 3.5 years specifically focused on Python. My proficiency lies in Python and its associated frameworks. Beyond that, I’ve delved into exciting domains such as Machine Learning (ML), Deep Learning, Natural Language Processing (NLP), and Computer Vision.  My track record boasts successful deploying end-to-end models, resulting in high-performing solutions. As a passionate developer, I’m driven to leverage my skills and contribute to impactful projects."

In [2]:
from nltk import sent_tokenize

doc = sent_tokenize(data)
doc

['As an IT professional with a total of 6 years of experience, including 3.5 years specifically focused on Python.',
 'My proficiency lies in Python and its associated frameworks.',
 'Beyond that, I’ve delved into exciting domains such as Machine Learning (ML), Deep Learning, Natural Language Processing (NLP), and Computer Vision.',
 'My track record boasts successful deploying end-to-end models, resulting in high-performing solutions.',
 'As a passionate developer, I’m driven to leverage my skills and contribute to impactful projects.']

In [3]:
from nltk import word_tokenize

doc = word_tokenize(data)
doc

['As',
 'an',
 'IT',
 'professional',
 'with',
 'a',
 'total',
 'of',
 '6',
 'years',
 'of',
 'experience',
 ',',
 'including',
 '3.5',
 'years',
 'specifically',
 'focused',
 'on',
 'Python',
 '.',
 'My',
 'proficiency',
 'lies',
 'in',
 'Python',
 'and',
 'its',
 'associated',
 'frameworks',
 '.',
 'Beyond',
 'that',
 ',',
 'I',
 '’',
 've',
 'delved',
 'into',
 'exciting',
 'domains',
 'such',
 'as',
 'Machine',
 'Learning',
 '(',
 'ML',
 ')',
 ',',
 'Deep',
 'Learning',
 ',',
 'Natural',
 'Language',
 'Processing',
 '(',
 'NLP',
 ')',
 ',',
 'and',
 'Computer',
 'Vision',
 '.',
 'My',
 'track',
 'record',
 'boasts',
 'successful',
 'deploying',
 'end-to-end',
 'models',
 ',',
 'resulting',
 'in',
 'high-performing',
 'solutions',
 '.',
 'As',
 'a',
 'passionate',
 'developer',
 ',',
 'I',
 '’',
 'm',
 'driven',
 'to',
 'leverage',
 'my',
 'skills',
 'and',
 'contribute',
 'to',
 'impactful',
 'projects',
 '.']

In [4]:
voc = list(set(doc))
voc

['Deep',
 '(',
 'frameworks',
 'NLP',
 'and',
 've',
 'Machine',
 'domains',
 'years',
 'deploying',
 'contribute',
 'including',
 'IT',
 'Learning',
 'total',
 'such',
 'skills',
 'exciting',
 'end-to-end',
 '6',
 'My',
 'into',
 'of',
 'ML',
 'high-performing',
 '3.5',
 '’',
 'with',
 'developer',
 'professional',
 'models',
 'to',
 'my',
 'resulting',
 'on',
 ')',
 'leverage',
 'that',
 'driven',
 'Processing',
 'an',
 'delved',
 'as',
 'track',
 'in',
 'Computer',
 'experience',
 'proficiency',
 'Beyond',
 'its',
 'Natural',
 'lies',
 'record',
 'Vision',
 'I',
 'passionate',
 'associated',
 'm',
 ',',
 'boasts',
 'a',
 'focused',
 'specifically',
 'Python',
 'impactful',
 '.',
 'projects',
 'Language',
 'successful',
 'solutions',
 'As']

In [5]:
len(voc)

71

In [6]:
doc.count(voc[1])

2

In [7]:
d = {}
for i in voc:
    d[i] = doc.count(i)
d

{'Deep': 1,
 '(': 2,
 'frameworks': 1,
 'NLP': 1,
 'and': 3,
 've': 1,
 'Machine': 1,
 'domains': 1,
 'years': 2,
 'deploying': 1,
 'contribute': 1,
 'including': 1,
 'IT': 1,
 'Learning': 2,
 'total': 1,
 'such': 1,
 'skills': 1,
 'exciting': 1,
 'end-to-end': 1,
 '6': 1,
 'My': 2,
 'into': 1,
 'of': 2,
 'ML': 1,
 'high-performing': 1,
 '3.5': 1,
 '’': 2,
 'with': 1,
 'developer': 1,
 'professional': 1,
 'models': 1,
 'to': 2,
 'my': 1,
 'resulting': 1,
 'on': 1,
 ')': 2,
 'leverage': 1,
 'that': 1,
 'driven': 1,
 'Processing': 1,
 'an': 1,
 'delved': 1,
 'as': 1,
 'track': 1,
 'in': 2,
 'Computer': 1,
 'experience': 1,
 'proficiency': 1,
 'Beyond': 1,
 'its': 1,
 'Natural': 1,
 'lies': 1,
 'record': 1,
 'Vision': 1,
 'I': 2,
 'passionate': 1,
 'associated': 1,
 'm': 1,
 ',': 7,
 'boasts': 1,
 'a': 2,
 'focused': 1,
 'specifically': 1,
 'Python': 2,
 'impactful': 1,
 '.': 5,
 'projects': 1,
 'Language': 1,
 'successful': 1,
 'solutions': 1,
 'As': 2}

In [8]:
import pandas as pd

df = pd.DataFrame(data=d.values(),index=d.keys(),columns=['count'])
df.head()

count
Deep            1
(               2
frameworks      1
NLP             1
and             3

In [11]:
print(dir(df))

['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__dataframe_consortium_standard__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', 

In [10]:
df.sort_values(by=['count'],ascending=0)

count
,               7
.               5
and             3
)               2
My              2
...           ...
that            1
driven          1
Processing      1
an              1
Deep            1

[71 rows x 1 columns]

In [12]:
df.reset_index()

index  count
0         Deep      1
1            (      2
2   frameworks      1
3          NLP      1
4          and      3
..         ...    ...
66    projects      1
67    Language      1
68  successful      1
69   solutions      1
70          As      2

[71 rows x 2 columns]

In [2]:
import numpy as np 

x = np.arange(0,100)

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
len(x)

100

In [5]:
y = np.linspace(0,100)

In [6]:
y

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [7]:
len(y)

50

In [8]:
a = np.linspace(0,100,100)
a

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [9]:
len(a)

100

In [10]:
np.random.rand(8)

array([0.37977134, 0.48228486, 0.14276394, 0.09512185, 0.91815936,
       0.70027121, 0.46906966, 0.44187009])

In [11]:
np.random.rand(2,2)

array([[0.67784146, 0.5085883 ],
       [0.22748427, 0.9647202 ]])

In [12]:
np.random.randint(3)

1

In [13]:
np.random.randint(2,90,size=[3,3])

array([[25,  6, 66],
       [25, 12, 83],
       [19,  8,  3]])

In [16]:
np.random.choice([12,3,4,5])

4

In [2]:
from nltk.stem import PorterStemmer

st = PorterStemmer()
doc = st.stem(data)
doc

'as an it professional with a total of 6 years of experience, including 3.5 years specifically focused on python. my proficiency lies in python and its associated frameworks. beyond that, i’ve delved into exciting domains such as machine learning (ml), deep learning, natural language processing (nlp), and computer vision.  my track record boasts successful deploying end-to-end models, resulting in high-performing solutions. as a passionate developer, i’m driven to leverage my skills and contribute to impactful projects.'

In [4]:
st.stem("history")

'histori'

In [5]:
st.stem("finally")

'final'

In [6]:
from nltk.stem import WordNetLemmatizer

l = WordNetLemmatizer()


In [7]:
l.lemmatize("history")

'history'

In [8]:
l.lemmatize("finally")

'finally'

In [11]:
l.lemmatize("working",pos='v')

'work'

In [16]:
import nltk
from nltk import word_tokenize

In [19]:
d = word_tokenize("Tajmahal is in India")

In [26]:
p = nltk.pos_tag(d)

In [32]:
p

[('Tajmahal', 'NNP'), ('is', 'VBZ'), ('in', 'IN'), ('India', 'NNP')]

In [31]:
print(nltk.ne_chunk(p))

(S (GPE Tajmahal/NNP) is/VBZ in/IN (GPE India/NNP))


In [34]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=19)

x = cv.fit_transform(d).toarray()
x

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0]], dtype=int64)

In [35]:
cv.vocabulary_

{'tajmahal': 3, 'is': 2, 'in': 0, 'india': 1}

In [38]:
import numpy as np 

a = np.array(d)
a.reshape(-1,1)

array([['Tajmahal'],
       ['is'],
       ['in'],
       ['India']], dtype='<U8')

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv2 = TfidfVectorizer()


x2 = cv2.fit_transform(d).toarray()
x2

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])