In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9779, 5513, 1251, 2686],
 [9779, 5513, 1251, 3662],
 [9779, 7321, 1251, 5258],
 [5924, 4987, 7409, 470, 8759],
 [5924, 4987, 7409, 470, 641],
 [1995, 9779, 8440, 1251, 7364],
 [5321, 4582, 7518, 470]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9779 5513 1251 2686]
 [   0    0    0    0 9779 5513 1251 3662]
 [   0    0    0    0 9779 7321 1251 5258]
 [   0    0    0 5924 4987 7409  470 8759]
 [   0    0    0 5924 4987 7409  470  641]
 [   0    0    0 1995 9779 8440 1251 7364]
 [   0    0    0    0 5321 4582 7518  470]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Nandeesh\git\kn_ml_course\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 188ms/step


array([[[-5.72295114e-03,  1.71792842e-02,  2.03714035e-02,
          4.03834619e-02,  4.68485691e-02,  1.95269473e-02,
         -2.05327868e-02, -1.57625191e-02,  4.86894734e-02,
         -2.72217281e-02],
        [-5.72295114e-03,  1.71792842e-02,  2.03714035e-02,
          4.03834619e-02,  4.68485691e-02,  1.95269473e-02,
         -2.05327868e-02, -1.57625191e-02,  4.86894734e-02,
         -2.72217281e-02],
        [-5.72295114e-03,  1.71792842e-02,  2.03714035e-02,
          4.03834619e-02,  4.68485691e-02,  1.95269473e-02,
         -2.05327868e-02, -1.57625191e-02,  4.86894734e-02,
         -2.72217281e-02],
        [-5.72295114e-03,  1.71792842e-02,  2.03714035e-02,
          4.03834619e-02,  4.68485691e-02,  1.95269473e-02,
         -2.05327868e-02, -1.57625191e-02,  4.86894734e-02,
         -2.72217281e-02],
        [-1.86065547e-02,  4.34421189e-02, -4.33200113e-02,
          2.79869698e-02, -4.80221882e-02, -1.93565376e-02,
          4.52075265e-02, -4.78743203e-02,  2.149972

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9779, 5513, 1251, 2686])

In [16]:
model.predict(embedded_docs[0])

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "c:\Nandeesh\git\kn_ml_course\venv\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\nande\AppData\Local\Temp\ipykernel_14692\2831431483.py", line 1, in <module>
    model.predict(embedded_docs[0],shape=embedded_docs[0].shape)
  File "c:\Nandeesh\git\kn_ml_course\venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "c:\Nandeesh\git\kn_ml_course\venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 119, in error_handler
    filtered_tb = _process_traceback_frames(e.__traceback__)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TensorFlowTrainer.predict() got an unexpected keyword argument 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Nandeesh\git\kn_